import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import ProviderWrapper from "@/client/utils/Provider";
import { Toaster } from "@/client/components/ui/toaster";
import SiteWrapper from "@/client/utils/SiteWarpper";

const inter = Inter({
  style: "normal",
  weight: "400",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SiteWrapper>{children}</SiteWrapper>
        <Toaster />
      </body>
    </html>
  );
}
